name: Java CI
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]
        java: [ '11', '17', '21' ]
        distribution: [ 'semeru', 'temurin' ]

    name: Test on ${{ matrix.os }} with Java ${{ matrix.java }} (${{ matrix.distribution }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --stacktrace
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x javadoc -x test
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs